UpgradeManager expose functions
digidem/mapeo-mobile pull request #547
Opened 2021-04-16 19:38 UTC by luandro

Solves #536

2021-04-19 20:01 UTC, gmaclennan requested changes
I have reviewed the code, but I have not reviewed the tests. I think there is some code that shouldn't be in here, probably because a rebase is needed?

2021-04-19 20:01 UTC, gmaclennan commented on src/backend/lib/upgrade-download.js
> -    if (this.context.upgrades.some(u => u.hash === upgrade.hash)) return false;
I think this needs to be rebased, this shouldn't be in here right?

2021-04-19 20:01 UTC, gmaclennan commented on src/backend/lib/upgrade-download.js
> +                this.setState(UpgradeState.Search.Searching, newContext);
Should this be in here?

2021-04-19 20:01 UTC, gmaclennan commented on src/backend/lib/upgrade-manager.js
> +  }
I think this should return state, not emit it.

2021-04-19 23:00 UTC, noffle commented on src/backend/lib/upgrade-download.js
> -    if (this.context.upgrades.some(u => u.hash === upgrade.hash)) return false;
right

2021-04-19 23:01 UTC, noffle commented
This is probably at least partly my fault. I did a force push late last week. Now that y'all are working on this branch too I'll refrain from that in the future.

2021-04-21 23:42 UTC, noffle commented
This should now be superceded by https://github.com/digidem/mapeo-mobile/pull/567

2021-04-21 23:42 UTC, closed without merging