Support downloading subsequent newer versions of the app
digidem/mapeo-mobile pull request #580
Opened 2021-04-30 16:50 UTC by noffle

This branch adds support for downloading multiple upgrades in a row. Previously the upgrade state machine would download at most **one** upgrade before locking itself into a state where it would download no more unless the app was restarted.

2021-05-06 15:16 UTC, gmaclennan requested changes
I think the original issue is because `DOWNLOADED` is not a state, it is an event. As far as I can see, we don't read or use this state anywhere. I think there are two possible states of the `Download` class:

1. `IDLE`
2. `DOWNLOADING`

The `download()` method transitions from `IDLE` --> `DOWNLOADING` and the events `error` or `download-complete` transition from `DOWNLOADING` --> `IDLE`. (I know we don't model those events as EventEmitter events, I'm referring them to abstract events caused by either the download failing or the download completing successfully).

In the future we might add a `cancelDownload()` method which would similarly transition `DOWNLOADING` --> `IDLE`.

I think the need for this reset method comes from modelling `DOWNLOADED` as a state, and what this PR does is essentially ensure that that state only exists for a single tick, because it immediately transitions that state to `IDLE`, so do we need it in the first place? It seems to add code complexity.

What does the search reset do? If the search is in the `SEARCHING` state does stopping and starting it force it to start finding things again?

2021-05-06 15:16 UTC, gmaclennan commented on src/backend/lib/upgrade-download.js
> +    if (this.state !== UpgradeState.Search.Searching) return;
My assumption would be that if the Search is in the `IDLE` state, then `reset()` would start the search (e.g. transition the Search state to `SEARCHING`), but `reset()` will only work if it is already `SEARCHING`. Is this how we want it to work? Should be documented for any future maintainers.

2021-05-07 01:37 UTC, noffle commented
>  I think there are two possible states of the Download class:   IDLE    DOWNLOADING

Ooh, I like this. I wrote this patch as a hack to try and fix a bug without *really* thinking through the bigger picture. I'll revise to include this idea.

> I think the need for this reset method comes from modelling DOWNLOADED as a state, and what this PR does is essentially ensure that that state only exists for a single tick, because it immediately transitions that state to IDLE, so do we need it in the first place? It seems to add code complexity.

The *actual* reason (which wasn't made obvious by just this diff) is that download options accumulate in the state's `context` object, which was confusing the logic in UpgradeManager, which decides which upgrade to download. I've revised how this works, so now the reset() logic isn't necessary.

The most recent changes also include a fix where, if there is a redownload (or multiple upgrade options in storage), the newest one wasn't being selected.

2021-05-10 21:16 UTC, gmaclennan approved these changes
Ok on a quick read-through this looks good, we can catch any issues we might have missed in QA on the share-apk-p2p branch. To address (not in this PR): put all the version compare logic in one place, to make it easier to implement https://github.com/digidem/mapeo-mobile/issues/578

2021-05-10 21:19 UTC, merged